sudo: required
services:
  - docker

before_install:
  - docker build -t gaggle -f Dockerfile.dev .

script:
  - docker run -e CI=true gaggle nx run-many --target=test --all

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "gaggle"
  env: "Gaggle-env-1"
  bucket_name: "elasticbeanstalk-us-east-1-131738280727"
  bucket_path: "gaggle"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
