sudo: required
services:
  - docker

before_install:
  - cd frontend
  - docker build -t gaggle -f Dockerfile.dev .

script:
  - docker run -e CI=true gaggle npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "gaggle"
  env: "Gaggle-env"
  bucket_name: "elasticbeanstalk-us-east-1-131738280727"
  bucket_path: "gaggle"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
