sudo: required
services:
  - docker
language: bash
on:
  branch: JY/aws-travis
access_key_id: $AWS_ACCESS_KEY
secret_access_key: $AWS_SECRET_KEY

before_install:
#  - docker build -t gaggle -f ./Dockerfile.test .
  - docker build . -t my-base-image:nx-base
script:
  - docker build -t jordanyono/gaggle -f ./apps/gaggle/Dockerfile .
#  - docker build -t jordanyono/gaggle-nginx -f ./nginx/Dockerfile .
  - docker build -t jordanyono/gaggle-api -f ./apps/api/Dockerfile .
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push jordanyono/gaggle
#  - docker push jordanyono/gaggle-nginx
  - docker push jordanyono/gaggle-api

#after_success:

# TODO
# Change back to main when done
#deploy:
#  provider: elasticbeanstalk
#  region: "us-east-1"
#  app: "gaggle"
#  env: "Gaggle-env-1"
#  bucket_name: "elasticbeanstalk-us-east-1-131738280727"
#  bucket_path: "gaggle"
#  on:
#    branch: main
#  access_key_id: $AWS_ACCESS_KEY
#  secret_access_key: $AWS_SECRET_KEY
#

# TODO remove
#  provider: elasticbeanstalk
#  region: "us-east-1"
#  app: "gaggle"
#  env: "Gaggle-env-1"
#  bucket_name: "elasticbeanstalk-us-east-1-131738280727"
#  bucket_path: "gaggle"


after_success:
  - docker-deploy/ecs.sh -c gaggle-production -n gaggle-production -i "https://hub.docker.com/repository/docker/jordanyono/gaggle-api:latest" -r "us-east-1" -t 240
