#version: '3.5'
#services:
#  gaggle:
#    image: gaggle
#    environment:
#      - apiPath=http://api:4000
#    ports:
#      - '4001:4001'
#  api:
#    image: api
#    ports:
#      - '4000:4000'
#  postgres:
#    image: 'postgres:latest'


version: '3.5'
services:
#  postgres:
#    image: 'postgres:latest'
#    environment:
#      - POSTGRES_PASSWORD=postgres_password
  nginx:
    depends_on:
      - api
      - gaggle
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - '3050:80'
  api:
    build:
      dockerfile: Dockerfile
      context: .
    volumes:
      - ./apps/api:/gaggle/apps/api
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PGUSER=postgres
      - PGHOST=postgres
      - PGDATABASE=postgres
      - PGPASSWORD=postgres_password
      - PGPORT=5432
    ports:
    - '4000:4000'
    command: ['node', 'dist/api/main.js']
  gaggle:
    stdin_open: true
    build:
      dockerfile: Dockerfile
      context: .
    volumes:
      - ./apps/gaggle:/gaggle/apps/gaggle
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    ports:
      - '4001:4001'
