version: '3.5'
services:
  postgres:
    image: 'postgres:latest'
    environment:
      - POSTGRES_PASSWORD=postgres_password
  nginx:
    depends_on:
      - api
      - gaggle
    restart: always
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - '3050:80'
  api:
    build:
      dockerfile: ./apps/api/Dockerfile.dev
      context: .
    volumes:
      - ./:/app
    environment:
      - PGUSER=postgres
      - PGHOST=postgres
      - PGDATABASE=postgres
      - PGPASSWORD=postgres_password
      - PGPORT=5432
    ports:
    - '4000:4000'
    command: ['npm', 'run', 'start-api']
  gaggle:
    stdin_open: true
    build:
      dockerfile: ./apps/gaggle/Dockerfile.dev
      context: .
    volumes:
      - ./:/app
    ports:
    - '4001:4001'
    command: [ 'npm', 'run', 'start-gaggle' ]
